spring.application.name=world-cup-qualification-engine
app.seed.enabled=false
app.fifa.base-url=https://api.fifa.com
app.fifa.id-competition=17
app.fifa.id-season=285023
app.fifa.id-stage-first=289273
